#version 450 core

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) buffer position_buffer {
	vec3 positions[];
};
layout (std430, binding = 1) buffer velocity_buffer {
	vec4 velocities[];
};

uniform float dt;

void main()
{
	uint id = gl_GlobalInvocationID.x;

	vec4 velocity = velocities[id];
	vec3 position = positions[id];

    vec3 new_position = position + velocity * dt;

	positions[id] = new_postition;
}
